version: '3'

services:
  site:
    image: leanlima/gerador_saudacoes:1.0
    ports:
      - "80:80"
    depends_on:
      - ms-pessoas-aleatorias
      - ms-saudacoes-aleatorias

  ms-pessoas-aleatorias:
    image: leanlima/ms-pessoas-aleatorias:1.0
    ports:
      - "8000:8000"

  ms-saudacoes-aleatorias:
    image: leanlima/ms-saudacoes-aleatorias:1.0
    ports:
      - "8080:8080"
